config/routes.rb
Rails.application.routes.draw do
  root 'organizations#index'
  get 'organizations/index'
  resources :organizations, only: [:show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
	validates :pod_id, presence: true, uniqueness: true
	validates :title, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :update]

  def index
    @organizations = Organization.all.order(:title)
    if @organizations.empty?
      get_organizations
    end
  end

  def show
    if @organization[:dataset].nil?
      @organization.update(dataset: get_dataset)
    end
    respond_to do |format|
      format.html
      format.zip { export_zip }
    end
  end

  def destroy
    Organization.destroy(params[:id])
    redirect_to root_path
  end


  private

  def export_zip
    require 'zip'
    compressed_filestream = Zip::OutputStream.write_buffer do |zos|
      @organization = Organization.find(params[:id])
      zos.put_next_entry "organization_#{@organization.pod_id}.json"
      zos.write @organization[:dataset]
    end

    compressed_filestream.rewind
    send_data compressed_filestream.read, filename: "org-#{@organization.pod_id}.zip"
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def get_organizations
    include_net_libs
    url = 'https://data.gov.ru/api/json/organization/?access_token=' + get_token
    uri = URI(url)
    response = Net::HTTP.get(uri)
    organizations = JSON.parse(response)

    organizations.each do |organization|
      Organization.create(pod_id: organization['id'], title: organization['title'])
    end
  end

  def get_dataset
    include_net_libs

    url = 'https://data.gov.ru/api/json/organization/' + @organization[:pod_id] + '/dataset/?access_token=' + get_token
    uri = URI(url)
    response = Net::HTTP.get(uri)

    response == "[]" ? "Для данной организации нет данных." : response
  end

  def get_token
    open('/usr/src/token').read
  end

  def include_net_libs
    require 'json'
    require 'net/http'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Src
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/organizations/index.html.slim
  table.table.table-striped
    thead
      tr
        th ID
        th Название
        th Запрос данных
    tbody
      - @organizations.each do |organization|
        tr
          td = organization[:pod_id]
          td = organization[:title]
          td[width="180"]
            - if organization[:dataset].nil?
              = link_to "Получить данные", organization
            - else
              = link_to 'Посмотреть данные', organization

app/views/organizations/show.html.slim
.container
  p
    | Идентификатор организации: 
    b = @organization[:pod_id]
  p
    | Название организации: 
    b = @organization[:title]
  br

  - if @organization[:dataset] != "Для данной организации нет данных."
    table.table.table-striped
      thead
        tr
          th Идентификатор
          th Название
          th Рубрика
      tbody
        - JSON.parse(@organization[:dataset]).each do |hash|
          tr
            td = hash['identifier']
            td = hash['title']
            td = hash['topic']

  - else
    - @status = true
    = @organization[:dataset]

  div[align="center"]
    - if @organization[:dataset] == "Для данной организации нет данных."
      = link_to 'Экспортировать данные', organization_path(format: :zip), class: "btn btn-secondary disabled"
    - else
      = link_to 'Экспортировать данные', organization_path(format: :zip), class: "btn btn-secondary"
    |  
    = link_to 'Удалить', @organization, method: :delete, data: { confirm: 'Это действие удалит организацию и все её данные из списка. Продолжить?' }, class: "btn btn-danger"